<?php
/*
 * @category: Magepow
 * @copyright: Copyright (c) 2014 Magepow (http://www.magepow.com/)
 * @licence: http://www.magepow.com/license-agreement
 * @author: MichaelHa
 * @create date: 2019-11-29 17:19:50
 * @LastEditors: MichaelHa
 * @LastEditTime: 2019-12-04 11:07:49
 */
?>
<?php
/**
 * Categories block
 *
 * @var $block \Magepow\Categories\Block\Categories
 */

$categories       = $block->getCategories();
$layout           = $block->getLayout();
$heading          = $block->getHeading();
$description      = $block->isShowDescription();

?>
<?php if (empty($categories)) return ?>
<?php if ($heading): ?>
    <h3 class="mx-0 my-4"><?php echo $heading ?></h3>
<?php endif; ?>
<ul class="category-grid w-full grid grid-flow-col auto-cols-max md:auto-cols-min">
    <?php foreach ($categories as $cat): ?>
        <li class="wrapper bg-primary">
            <a class="category" href="<?php echo $cat->getUrl() ?>">
                <div class="category-image">
                    <img src="<?php echo $this->getImage($cat) ?>" alt="<?php echo $cat->getName() ?>"/>
                </div>
                <div class="category-name">
                    <span><?php echo $cat->getName() ?></span>
                </div>
            </a>
            <?php if($description): ?>
                <div class="category-description">
                    <?php echo $this->getDescription($cat) ?>
                </div>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>
