<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use HyvaThemes\Magento2MagepowCategories\ViewModel\Resize;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Resize $resize */

$resize = $viewModels->require(Resize::class);

$categories = $block->getCategories();
$layout = $block->getLayout();
$heading = $block->getHeading();
$description = $block->isShowDescription();
?>

<script>
    function init() {
        return {
            layout: '<?=$block->getLayout(); ?>',
        }

    }
</script>
<div class="container">
    <?php if (empty($categories)) return ?>
    <?php if ($heading): ?>
        <h3 class="mx-0 my-1"><?php echo $heading ?></h3>
    <?php endif; ?>
    <div x-data="init()" :class="{ 'grid gap-4 grid-cols-1 sm:grid-cols-2 md:grid-cols-4 lg:grid-cols-6': layout == 'grid' }">
        <?php foreach ($categories as $cat): ?>
            <div class="bg-transparent border-gray-200-lighter border mr-2 mb-2" :class="{ 'flex mb-2': layout == 'list' }">
                <div :class="{ 'pr-2': layout == 'list' }">
                    <a href="<?php echo $cat->getUrl() ?>">
                        <div class="p-1 m-auto text-secondary text-center">
                            <img loading="lazy" width="222" height="222" class="m-auto" src="<?php echo $resize->resize($cat->getImage(),222); ?>" alt="<?php echo $cat->getName() ?>"/>
                        </div>
                        <div class="text-sm break-words m-auto text-secondary text-center font-bold uppercase ">
                            <?php echo $cat->getName() ?>
                        </div>
                    </a>
                </div>
                <?php if ($description): ?>
                    <div class="m-auto w-full text-secondary text-left">
                        <?php echo $this->getDescription($cat) ?>
                    </div>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>
