<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use HyvaThemes\Magento2MagepowCategories\ViewModel\Resize;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Resize $resize */
/** @var Escaper $escaper */

$resize = $viewModels->require(Resize::class);

$categories = $block->getCategories();
$layout = $block->getLayout();
$heading = $block->getHeading();
$description = $block->isShowDescription();
?>

<script>
    function init() {
        return {
            layout: '<?=$block->getLayout(); ?>',
        }

    }
</script>
<div class="container">
    <?php if (empty($categories)) return ?>
    <?php if ($heading): ?>
        <h3 class="mx-0 my-1"><?= $escaper->escapeHtml($heading) ?></h3>
    <?php endif; ?>
    <div x-data="init()"
         :class="{'category-grid grid gap-4 grid-cols-1 sm:grid-cols-2 md:grid-cols-4 lg:grid-cols-6': layout == 'grid' }">
        <?php foreach ($categories as $cat): ?>
            <div class="bg-transparent border-gray-200-lighter border" :class="{ 'flex mb-2': layout == 'list' }">
                <div :class="{ 'pr-2': layout == 'list' }">
                    <a aria-label="<?= $escaper->escapeHtml($cat->getName()) ?> Image Link" href="<?= $cat->getUrl() ?>">
                        <div class="p-1 m-auto text-secondary text-center">
                            <img loading="lazy" width="222" height="222" class="m-auto"
                                 src="<?= $resize->resize($cat->getImage(), 222); ?>"
                                 title="<?= $escaper->escapeHtml($cat->getName()) ?>"
                                 alt="<?= $escaper->escapeHtml($cat->getName()) ?>"/>
                        </div>
                    </a>
                    <div class="text-sm break-words m-auto text-secondary text-center font-bold uppercase ">
                        <a aria-label="<?= $escaper->escapeHtml($cat->getName()) ?>" href="<?= $cat->getUrl() ?>">
                            <?= $escaper->escapeHtml($cat->getName()) ?>
                        </a>
                    </div>

                </div>
                <?php if ($description): ?>
                    <div class="m-auto w-full text-secondary text-left">
                        <?= $escaper->escapeHtml($this->getDescription($cat)) ?>
                    </div>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>
